### ISSUE TITLE
Official blob tutorial is not working

### ISSUE THREAD

**Issue by ronnylt** [remix-run/examples#140]
`_official-blog-tutorial` example is not working.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || 17.x" from @reach/alert@0.17.0
npm ERR! node_modules/@reach/alert
npm ERR!   @reach/alert@"^0.17.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

Reach UI does not support React 18 yet (https://github.com/reach/reach-ui/issues/916).

We can remove Reach UI dependency here and use any other thing that supports React 18. I can work on a fix if you agree to do so.

**Comment by ronnylt** [comment]
Replaced the `@reach/alert` stuff with simple markup, but now getting other error: 

```
npm run dev      

> dev
> run-p "dev:*"


> dev:remix
> node --require ./mocks ./node_modules/.bin/remix dev


> dev:css
> npm run generate:css -- --watch

/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:4810
        throw error;
        ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/headers-polyfill/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Function.Module._resolveFilename (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:4768:36)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.newLoader (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:4807:24)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/http.get.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.newLoader (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:4807:24)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/index.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.newLoader (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:4807:24)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/msw/node/lib/index.js:5:21)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.newLoader (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:4807:24)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/mocks/start.ts:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._compile (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.newLoader [as .ts] (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/ronnylt/Workspace/ronnylt/remix/remix-examples/_official-blog-tutorial/mocks/index.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1342:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:583:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:95:3)
    at node:internal/main/run_main_module:9:1 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
ERROR: "dev:remix" exited with 1.
```
