### ISSUE TITLE
auth0 example is broken

### ISSUE THREAD

**Issue by sdroscher** [remix-run/examples#177]
Trying to run the `remix-auth-auth0` locally or in Codesandbox results in the following error when you click the login button:

```
TypeError: Cannot read property 'startsWith' of undefined
    at Auth0Strategy.getCallbackURL (/sandbox/node_modules/remix-auth-oauth2/build/index.js:182:30)
    at Auth0Strategy.authenticate (/sandbox/node_modules/remix-auth-oauth2/build/index.js:78:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.callRouteActionRR (/sandbox/node_modules/@remix-run/server-runtime/dist/data.js:24:16)
    at callLoaderOrAction (/sandbox/node_modules/@remix-run/router/router.ts:3125:14)
    at submit (/sandbox/node_modules/@remix-run/router/router.ts:2609:16)
    at queryImpl (/sandbox/node_modules/@remix-run/router/router.ts:2544:22)
    at Object.queryRoute (/sandbox/node_modules/@remix-run/router/router.ts:2494:18)
    at handleDataRequestRR (/sandbox/node_modules/@remix-run/server-runtime/dist/server.js:81:20)
    at requestHandler (/sandbox/node_modules/@remix-run/server-runtime/dist/server.js:55:18)
```

**Comment by alsherko** [comment]
@sdroscher I think you just need setup `.env` file. Check `.env.example` in `remix-auth-auth0`
