### ISSUE TITLE
[Feature Request] Framework user wants to have an example integration with Cloudscape Design System

### ISSUE THREAD

**Issue by build-failure** [remix-run/examples#294]
As a framework user I want to utilize [Remix](https://remix.run/) in conjunction with the [Cloudscape Design System](https://cloudscape.design/get-started/integration/using-cloudscape-components/). To unterstand the basic integration details I want to have an example for that within [remix-run/examples repository](https://github.com/remix-run/examples).

# Acceptance Criteria
- Example integration between Remix and Cloudscape Design System exists
- Example intergration shows rendering of Cloudscape Design System components and related styles.

# Background
I would like to integrate and use [Cloudscape](https://cloudscape.design/get-started/integration/using-cloudscape-components/) as the front-end component design system. Unfortunately I'm stuck with the example integration trying to follow both guides:
https://remix.run/docs/en/main/guides/styling
https://cloudscape.design/get-started/integration/using-cloudscape-components/
The example integration code is currently stored here - https://github.com/build-failure/remix-examples/tree/cloudscape/cloudscape. It can be tested within [codesandbox.io](http://codesandbox.io/) - https://codesandbox.io/p/sandbox/github/build-failure/remix-examples/tree/cloudscape/cloudscape.
AFAIK Cloudscape is using CSS Side-Effect Imports, thus I followed the last integration scenario - https://remix.run/docs/en/main/guides/styling#css-side-effect-imports.
While the global styles are loaded properly, styles for the particular components are not loaded.
Additionally I'm receiving server side errors (can be viewed at https://codesandbox.io/p/sandbox/github/build-failure/remix-examples/tree/cloudscape/cloudscape):
```
Remix App Server started at http://localhost:3000/ (http://192.168.241.2:3000/)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at InternalContainer (/project/sandbox/build/index.js:899:9)
    at AnalyticsFunnelSubStep (/project/sandbox/build/index.js:938:33)
    at Container (/project/sandbox/build/index.js:952:9)
    at div
    at div
    at InternalSpaceBetween (/project/sandbox/build/index.js:996:9)
    at SpaceBetween (/project/sandbox/build/index.js:1006:9)
    at body
    at html
    at App (/project/sandbox/build/index.js:1638:55)
    at RemixRoute (/project/sandbox/node_modules/@remix-run/react/dist/components.js:71:3)
    at RenderedRoute (/project/sandbox/node_modules/react-router/dist/umd/react-router.development.js:680:7)
    at RenderErrorBoundary (/project/sandbox/node_modules/react-router/dist/umd/react-router.development.js:624:7)
    at Routes (/project/sandbox/node_modules/react-router/dist/umd/react-router.development.js:1174:7)
    at Router (/project/sandbox/node_modules/react-router/dist/umd/react-router.development.js:1106:17)
    at StaticRouterProvider (/project/sandbox/node_modules/react-router-dom/server.js:67:3)
    at RemixErrorBoundary (/project/sandbox/node_modules/@remix-run/react/dist/errorBoundaries.js:24:5)
    at RemixServer (/project/sandbox/node_modules/@remix-run/react/dist/server.js:47:3)
```
While there are proposals on how to fix that (https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85), I'm not sure how to achieve this...

**Comment by MichaelDeBoey** [comment]
@build-failure As this is a community examples repo, we rely on community members to provide examples

We'd be happy to accept a PR if you want to add your mentioned example
