### ISSUE TITLE
with twind example has some error

### ISSUE THREAD

**Issue by Alvazz** [remix-run/examples#76]
Error: Cannot find module '/sandbox/build/index.js'
Require stack:
- /sandbox/node_modules/@remix-run/serve/dist/index.js
- /sandbox/node_modules/@remix-run/dev/dist/cli/commands.js
- /sandbox/node_modules/@remix-run/dev/dist/cli/run.js
- /sandbox/node_modules/@remix-run/dev/dist/cli/index.js
- /sandbox/node_modules/@remix-run/dev/dist/index.js
- /sandbox/node_modules/@remix-run/dev/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /sandbox/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/sandbox/node_modules/express/lib/router/layer.js:95:5)
    at next (/sandbox/node_modules/express/lib/router/route.js:144:13)
    at next (/sandbox/node_modules/express/lib/router/route.js:140:7)
    at next (/sandbox/node_modules/express/lib/router/route.js:140:7)
    at next (/sandbox/node_modules/express/lib/router/route.js:140:7)

**Comment by leapful** [comment]
@Alvazz 

For local development:

`yarn build` or `npm run build`

Otherwise:

```
yarn build
yarn start
```

OR

```
npm run build
npm run start
```

**Comment by machour** [comment]
I can confirm that I'm able to run the example using `yarn dev`

@Alvazz if this is still not working for you, please open a new issue giving more details about your OS / node version, and how you compiled / ran the example 🙏🏼
